# Generate the certificate into the working folder.
['landscape/certificate.pdf']
author='Author Name'

# If the specified certificate is not <working folder>/certificate.pdf, then we'll just copy it over (if it exists).
['square/square-certificate.pdf']
author='Overwrite Inline'